name: Build and Push to Quay

on:
  push:
    branches:
      - main

env:
  FULL_IMAGE: quay.io/marclv10/shift_left:v1

jobs:
  build-scan-push:
    runs-on: ubuntu-latest

    steps:
      - name: üß© Checkout code
        uses: actions/checkout@v4

      - name: üîß Build container image
        run: |
          docker build -t $FULL_IMAGE .

      - name: üîç Scan image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.FULL_IMAGE }}
          severity: HIGH,CRITICAL
          exit-code: 1
          ignore-unfixed: true
      
      # Generate SBOM with Syft (syft-json format)
      - name: Generate SBOM (Syft)
        run: |
         docker run --rm \
          -v /var/run/docker.sock:/var/run/docker.sock \
          -v "$PWD":/work \
          anchore/syft:latest "$FULL_IMAGE" --output syft-json=/work/sbom.syft.json
         test -s sbom.syft.json && echo "SBOM created: sbom.syft.json"

         
      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
         name: sbom-syft-json
         path: sbom.syft.json
         if-no-files-found: error
         retention-days: 14
         
       # Evaluate SBOM with Grype (fail build on HIGH or CRITICAL vulns)
      - name: Vulnerability scan (Grype on SBOM)
        run: |
          docker run --rm \
            -v "$PWD":/work \
            anchore/grype:latest /work/sbom.syft.json \
            --fail-on critical \
            --only-fixed=false
 

      - name: üîë Login to Quay.io
        run: |
          docker login quay.io -u "${{ secrets.QUAY_USER }}" -p "${{ secrets.QUAY_PASSWORD }}"

      - name: üöÄ Push image to Quay.io
        run: |
          docker push $FULL_IMAGE
      
      - name: Commit SBOM to Git repo
        run: |
          git config user.email "github-actions@github.com"
          git config user.name "GitHub Actions"

          mkdir -p sbom
          cp sbom.syft.json sbom/sbom.syft.json

          git add sbom/sbom.syft.json
          git commit -m "Add SBOM from pipeline" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.TOKEN_GIT }}@github.com/Marc102003/shift_left.git main

